
---
- hosts: all
  gather_facts: no
  tasks:
    - name: test connection
      ping:
    - name: verify postgres is installed
      become: yes
      apt:
        name: postgresql
        state: present
    - name: verify rabbit is installed
      become: yes
      apt:
        name: rabbitmq-server
        state: present
        
